---
- hosts: all
  become_user: root
  become_method: sudo
  tasks:
    - name: Include OS-specific variables.
      include_vars: "{{ playbook_dir }}/defaults/main.yml"
  roles:
    - { role: elasticsearch }
    - { role: wazuh-manager }
    - { role: wazuh-agent }
    - { role: instructions }
