---
- name: Setup Redis Systemd
  template:
    src: systemd-redis.j2
    dest: "/etc/systemd/system/redis.service"
    mode: 0644
  become: true
  when: redis_role != "sentinel"

- name: Setup Redis Sentinel Systemd
  template:
    src: systemd-sentinel.j2
    dest: "/etc/systemd/system/redis-sentinel.service"
    mode: 0644
  become: true

- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: true
  when: "systemd_check.stat.exists == true"

- name: Ensure Redis is is started on runtime
  systemd:
    name: redis
    enabled: yes
  become: true
  when: redis_role != "sentinel"

- name: Ensure Redis is is started on runtime
  systemd:
    name: redis-sentinel
    enabled: yes
  become: true
