- name: Stop Wazuh Agent
  service:
    name: wazuh-agent
    state: stopped

- name:  Configure filebeat wazuh-agent
  template:
    src: "config/ossec.conf.j2"
    dest: "/var/ossec/etc/ossec.conf"

- name: Retart Wazuh Agent
  service:
    name: wazuh-agent
    state: restarted
    enabled: yes

#- name: Connect wazuh-ahent
#  command: "/var/ossec/bin/agent-auth -m {{ wazuh_manager_ip }}"
